name: Generate Snk

on:
  push:
    branches:
      - main
  schedule:
    - cron: '13 2 * * *'

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: output
    - uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          github-contribution-grid-snake.svg?color_snake=#B04078&color_dots=#64A1F4,#4B91F1,#3C7DD9,#bfd6f6,#8dbdff
    - name: Commit and push
      run: |
        git add .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Generated snake"
        git push
